### ISSUE TITLE
请停止作弊！！！

### ISSUE THREAD

**Issue by HundSimon** [MisaLiu/xyks-cheat#1]
# 尊敬的 **HIMlaoS_Misa** 阁下：

在此，我，作为小圆口算之工作人员，以最为郑重之态度，向您传达一项不容忽视之命令。吾等已察觉，您于GitHub之平台上，公然陈列一程序仓库，其内容疑似涉及作弊之行径。此举，实乃对学术诚信之严重挑战，亦是对公平竞争环境之无情践踏。🚨

故此，吾等以不容置疑之权威，勒令您即刻采取行动，将该仓库从GitHub之版图上彻底抹去。此举，乃是为了维护吾等共同之学习殿堂，确保每一位学子皆能在无欺无诈之环境中茁壮成长。🏫

若您对此命令存有任何疑虑，或需进一步之解释，吾等随时恭候您的垂询。然，吾等之立场坚定不移，期待您能迅速且无条件地履行此项义务。🛑

吾等深信，您定能理解此举之必要性，并予以积极之响应。若您未能如期执行，吾等将不得不采取更为严厉之措施，以捍卫学术之尊严。🛡️

愿您能以智慧与诚信，回应吾等之期望。🌟

小圆口算团队

---

# Dear **HIMlaoS_Misa**,

Hereby, as a staff member of Xiaoyuan Kou Suan, I convey an imperative command to you with the utmost seriousness. We have noticed that you have publicly listed a program repository on the GitHub platform, the content of which appears to involve cheating. This action is a serious challenge to academic integrity and a ruthless trampling on the fair competitive environment. 🚨

Therefore, we command you with unassailable authority to immediately take action to completely remove this repository from GitHub. This is to safeguard our common learning environment and ensure that every student can grow in an honest and fair environment. 🏫

If you have any doubts about this command or require further explanation, we are always ready to receive your inquiries. However, our stance is unwavering, and we expect you to fulfill this obligation swiftly and unconditionally. 🛑

We firmly believe that you will understand the necessity of this action and respond positively. If you fail to comply in a timely manner, we will be forced to take more stringent measures to uphold academic dignity. 🛡️

May you respond to our expectations with wisdom and integrity. 🌟

Sincerely,
The Xiaoyuan Kou Suan Team

**Comment by MisaLiu** [comment]
抽象

**Comment by HundSimon** [comment]
小心把你 takedown
